export const APP_VERSION = "0.1.0-mvp";

export const SETTINGS = {
  practiceMaxSeconds: 20,
  practiceHitsToStart: 3,
  sessionSeconds: 120,
  phaseSeconds: {
    stable: 40,
    drift: 80,
    recovery: 120,
  },
  orbitRadius: 72,
  orbitPeriodSeconds: 1.65,
  projectileSpeed: 520,
  targetRadius: 32,
  hitGraceRadius: 36,
  nodeRadius: 20,
  minTargetDistance: 245,
  maxTargetDistance: 335,
  rapidTapWindowSeconds: 0.35,
  missResetSeconds: 0.38,
  hitSettleSeconds: 0.08,
  shields: {
    max: 10,
    startByLevel: {
      easy: 10,
      medium: 9,
      difficult: 8,
    },
    missCost: 1,
    rapidTapCost: 0,
    normalHitGain: 1,
    coreHitGain: 1,
    bullseyeHitGain: 2,
    levelClearGain: 2,
  },
  volatility: {
    driftChance: 0.58,
    driftDelayMinSeconds: 0.55,
    driftDelayMaxSeconds: 1.55,
    driftDurationMinSeconds: 0.62,
    driftDurationMaxSeconds: 0.95,
    driftMinDistance: 34,
    driftMaxDistance: 76,
  },
  scoring: {
    baseByQuality: {
      graze: 25,
      hit: 60,
      core: 120,
      bullseye: 220,
    },
    comboStep: 0.1,
    maxComboMultiplier: 3,
    overdriveMultiplierBonus: 0.5,
    overdriveEvery: 10,
    overdriveSeconds: 5,
    streakBonusEvery: 5,
    streakBonus: 100,
    bonusComet: 150,
  },
};

export const LEVELS = [
  {
    id: "easy",
    label: "Tutorial Orbit",
    shortLabel: "Wide Orbit",
    orbitPeriodSeconds: 1.95,
    projectileSpeed: 500,
    orbitRadius: 72,
    targetRadius: 68,
    gravityRadius: 120,
    minTargetDistance: 230,
    maxTargetDistance: 315,
    successesToComplete: 3,
    completionBonus: 180,
    timingWindowSeconds: 0.16,
    targetMotion: { enabled: false },
  },
  {
    id: "chain-reaction",
    label: "Chain Reaction",
    shortLabel: "Streak fuel",
    orbitPeriodSeconds: 1.82,
    projectileSpeed: 510,
    orbitRadius: 72,
    targetRadius: 62,
    gravityRadius: 108,
    minTargetDistance: 235,
    maxTargetDistance: 320,
    successesToComplete: 4,
    completionBonus: 220,
    timingWindowSeconds: 0.15,
    targetMotion: { enabled: false },
    streakRewardLevel: true,
  },
  {
    id: "tight-window",
    label: "Tight Window",
    shortLabel: "Sharper timing",
    orbitPeriodSeconds: 1.72,
    projectileSpeed: 530,
    orbitRadius: 72,
    targetRadius: 56,
    gravityRadius: 94,
    minTargetDistance: 250,
    maxTargetDistance: 330,
    successesToComplete: 4,
    completionBonus: 260,
    timingWindowSeconds: 0.105,
    targetMotion: { enabled: false },
  },
  {
    id: "medium",
    label: "Wandering Planet",
    shortLabel: "Moving Planets",
    orbitPeriodSeconds: 1.62,
    projectileSpeed: 545,
    orbitRadius: 72,
    targetRadius: 52,
    gravityRadius: 90,
    minTargetDistance: 250,
    maxTargetDistance: 335,
    successesToComplete: 4,
    completionBonus: 300,
    timingWindowSeconds: 0.12,
    targetMotion: {
      enabled: true,
      chance: 0.35,
      amplitudeMin: 20,
      amplitudeMax: 28,
      periodSecondsMin: 3,
      periodSecondsMax: 4.2,
      freezeOnLaunch: true,
    },
  },
  {
    id: "fast-orbit",
    label: "Fast Orbit",
    shortLabel: "Quick release",
    orbitPeriodSeconds: 1.28,
    projectileSpeed: 580,
    orbitRadius: 70,
    targetRadius: 48,
    gravityRadius: 80,
    minTargetDistance: 260,
    maxTargetDistance: 345,
    successesToComplete: 4,
    completionBonus: 340,
    timingWindowSeconds: 0.105,
    targetMotion: {
      enabled: true,
      chance: 0.35,
      amplitudeMin: 20,
      amplitudeMax: 28,
      periodSecondsMin: 3,
      periodSecondsMax: 4.2,
      freezeOnLaunch: true,
    },
  },
  {
    id: "heavy-gravity",
    label: "Heavy Gravity",
    shortLabel: "Wide pull",
    orbitPeriodSeconds: 1.5,
    projectileSpeed: 535,
    orbitRadius: 74,
    targetRadius: 50,
    gravityRadius: 118,
    minTargetDistance: 260,
    maxTargetDistance: 345,
    successesToComplete: 4,
    completionBonus: 360,
    timingWindowSeconds: 0.115,
    grazeScoreMultiplier: 0.72,
    targetMotion: {
      enabled: true,
      chance: 0.35,
      amplitudeMin: 20,
      amplitudeMax: 28,
      periodSecondsMin: 3,
      periodSecondsMax: 4.2,
      freezeOnLaunch: true,
    },
  },
  {
    id: "difficult",
    label: "Flicker Window",
    shortLabel: "Fast + Tight",
    orbitPeriodSeconds: 1.2,
    projectileSpeed: 600,
    orbitRadius: 72,
    targetRadius: 42,
    gravityRadius: 68,
    minTargetDistance: 265,
    maxTargetDistance: 350,
    successesToComplete: 5,
    completionBonus: 420,
    timingWindowSeconds: 0.095,
    flickerWindow: true,
    targetMotion: {
      enabled: true,
      chance: 0.65,
      amplitudeMin: 28,
      amplitudeMax: 42,
      periodSecondsMin: 2.2,
      periodSecondsMax: 3.2,
      freezeOnLaunch: true,
    },
  },
  {
    id: "twin-planets",
    label: "Twin Planets",
    shortLabel: "Bonus comet",
    orbitPeriodSeconds: 1.18,
    projectileSpeed: 610,
    orbitRadius: 72,
    targetRadius: 40,
    gravityRadius: 66,
    minTargetDistance: 270,
    maxTargetDistance: 355,
    successesToComplete: 5,
    completionBonus: 460,
    timingWindowSeconds: 0.095,
    bonusCometChance: 0.7,
    targetMotion: {
      enabled: true,
      chance: 0.65,
      amplitudeMin: 28,
      amplitudeMax: 42,
      periodSecondsMin: 2.2,
      periodSecondsMax: 3.2,
      freezeOnLaunch: true,
    },
  },
  {
    id: "red-giant",
    label: "Red Giant",
    shortLabel: "Boss planet",
    orbitPeriodSeconds: 1.08,
    projectileSpeed: 630,
    orbitRadius: 72,
    targetRadius: 46,
    gravityRadius: 72,
    minTargetDistance: 275,
    maxTargetDistance: 360,
    successesToComplete: 8,
    completionBonus: 700,
    timingWindowSeconds: 0.09,
    bonusCometChance: 0.45,
    goldChance: 0.38,
    boss: true,
    targetMotion: {
      enabled: true,
      chance: 0.65,
      amplitudeMin: 28,
      amplitudeMax: 42,
      periodSecondsMin: 2.2,
      periodSecondsMax: 3.2,
      freezeOnLaunch: true,
    },
  },
];

export const DEMO_RULES = {
  id: "demo",
  label: "Demo",
  orbitPeriodSeconds: 2.12,
  projectileSpeed: 440,
  orbitRadius: 72,
  targetRadius: 86,
  gravityRadius: 152,
  minTargetDistance: 205,
  maxTargetDistance: 270,
  successesToComplete: 3,
  completionBonus: 0,
  targetMotion: { enabled: false },
};

export const TARGET_STAGES = [
  {
    id: "white",
    label: "White",
    core: "rgba(255,255,255,0.98)",
    ring: "rgba(255,255,255,0.42)",
    glow: "rgba(255,255,255,0.42)",
  },
  {
    id: "yellow",
    label: "Yellow",
    core: "rgba(255,232,126,0.98)",
    ring: "rgba(255,232,126,0.52)",
    glow: "rgba(255,232,126,0.44)",
  },
  {
    id: "orange",
    label: "Orange",
    core: "rgba(255,156,72,0.98)",
    ring: "rgba(255,156,72,0.58)",
    glow: "rgba(255,156,72,0.5)",
  },
  {
    id: "red",
    label: "Red",
    core: "rgba(255,72,82,0.98)",
    ring: "rgba(255,72,82,0.7)",
    glow: "rgba(255,72,82,0.62)",
  },
];

export const TAU = Math.PI * 2;
